#!/usr/bin/env php
<?php

declare(strict_types=1);

$autoload = [
    getcwd() . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
];
foreach ($autoload as $file) {
    if (is_file($file)) {
        require $file;
    }
}

use APITester\Command\ExecutePlanCommand;
use PHPUnit\Util\TestDox\CliTestDoxPrinter;
use Symfony\Component\Console\Application;

new CliTestDoxPrinter(); //hack should find a solution to autoload
$application = new Application('api-tester', '0.1');
$application->add(new ExecutePlanCommand());
$application->setDefaultCommand('launch', true);
$application->run();
