#!/usr/bin/env php
<?php

declare(strict_types=1);

$autoload = [
    getcwd() . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
];

$loaded = false;
foreach ($autoload as $file) {
    if (is_file($file)) {
        require_once $file;
        $loaded = true;
        break;
    }
}

if (!$loaded) {
    fwrite(STDERR, "Could not find Composer autoload.php.\n");
    exit(1);
}

use APITester\Command\ExecutePlanCommand;
use Symfony\Component\Console\Application;

$application = new Application('api-tester', '0.1');
$application->add(new ExecutePlanCommand());
$application->setDefaultCommand('launch', true);
$application->run();
