name: Code Analysis

on:
    pull_request: ~
    push:
        branches:
            - master
            - lib

jobs:
    code-validation:
        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -   name: PHPStan
                        run: composer phpstan

                    -   name: Psalm
                        run: composer psalm

                    -   name: Ecs
                        run: composer check-cs

                    -   name: PHPUnit
                        run: composer unit
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: pcov
                    tools: composer:v2

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   run: ${{ matrix.actions.run }}

            -   name: Coverage diff
                uses: OpenClassrooms/coverage-checker@v1.7.0
                if: ${{ hashFiles('build/coverage/coverage.xml') != '' && github.event_name == 'pull_request' }}
                with:
                    action: check
                    files: '[{"coverage": "build/coverage/coverage.xml", "summary": "coverage-summary.json", "label": "Coverage", "badge": "coverage.svg"}]'
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Coverage update
                uses: OpenClassrooms/coverage-checker@v1.7.0
                if: ${{ hashFiles('build/coverage/coverage.xml') != '' && github.event_name == 'push' && (github.ref_name == 'lib' || github.ref_name == 'master') }}
                with:
                    action: update
                    files: '[{"coverage": "build/coverage/coverage.xml", "summary": "coverage-summary.json", "label": "Coverage", "badge": "coverage.svg"}]'
                    token: ${{ secrets.GITHUB_TOKEN }}
