name: Analysis

on: [ push, pull_request ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v3

  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://vimeo/psalm-github-actions

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpstan@v2

  ecs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zingimmick/ecs-action@0.0.4
