name: Install

on:
    workflow_call: ~
jobs:
    install:
        name: PHP & Composer install
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: pcov
                    tools: composer:v2

            #            -   name: Get composer cache directory
            #                id: composer-cache
            #                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            #
            #            -   name: Cache dependencies
            #                uses: actions/cache@v2
            #                with:
            #                    path: ${{ steps.composer-cache.outputs.dir }}
            #                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            #                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress
            -   run: ls -lha
            -   run: ls -lha ./vendor/bin
            -   run: composer psalm
            -   name: ZIP project
                run: zip build.zip ./* -r
            -   name: Upload output file
                uses: actions/upload-artifact@v2
                with:
                    name: build
                    path: build.zip
